### ISSUE TITLE
Floor vs Ceil?

### ISSUE THREAD

**Issue by tloriato** [maxd13/Analise_AlgoritmosT1#1]
Wasn't this supposed to be floor? 
 
https://github.com/maxd13/Analise_AlgoritmosT1/blob/14f64b581862fcb2879ce1868fb2e2d1fee2e226/linear_select.py#L27

**Comment by maxd13** [comment]
No. If I wanted to floor it I would just use // 2, which is integer division in Python 3, apparently.

I ceil it there because if it is not divisible by 2 it should be the next one, to compensate for the line "return sorted(ls)[k - 1]"

If the list has length 5, diving by 2 and ceilling gives 3, which is passed as the k. Then the return will get position 2 of the array which is the third position of it.
